### ISSUE TITLE
Not everyone receiving rewards for watching an advert

### ISSUE THREAD

**Issue by BlueOrange775** [LinhyCZ/MOTDgd_Unturned#2]
Ive recently had some information brought to my attention that people who have watched a 30 second advert have not gotten their rewards. I have the latest build.

**Comment by LinhyCZ** [comment]
This issue was caused by server-code not working properly. It is already fixed. If this issue persist, download newest version (Build #12) and open new issue providing more information (Config file, console log with AdvancedLogging on)
