### ISSUE TITLE
Experiencing "Requesting your ad" with no popup or anything

### ISSUE THREAD

**Issue by BlueOrange775** [LinhyCZ/MOTDgd_Unturned#3]
Hi there,
For these past few builds I have been experiencing this issue multiple times, and its where someone does /ad and it just says "Requesting your ad" in chat, nothing else past that point. The following is what happens in console after doing /ad with nothing else happening

`MOTDgd >> Requesting ad link for player Emperor | BlueOrange with CSteamID 76561198043920423 and IP xxx.xxx.xxx.xxx
MOTDgd >> Received link for player Emperor | BlueOrange with CSteamID 76561198043920423
MOTDgd >> Received link on login for player Emperor | BlueOrange - link = http://motdgd.c...
`

**Comment by LinhyCZ** [comment]
For now, ad should appear when player moves. Will be fixed in other build.
